-- MySQL Script generated by MySQL Workbench
-- Thu Jan 26 11:27:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetointegrador_ods1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetointegrador_ods1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetointegrador_ods1` DEFAULT CHARACTER SET utf8 ;
USE `projetointegrador_ods1` ;

-- -----------------------------------------------------
-- Table `projetointegrador_ods1`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetointegrador_ods1`.`usuario` (
  `id` INT NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetointegrador_ods1`.`tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetointegrador_ods1`.`tema` (
  `id` INT NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetointegrador_ods1`.`postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetointegrador_ods1`.`postagem` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(200) NOT NULL,
  `mensagem` VARCHAR(500) NOT NULL,
  `data_postagem` DATE NULL,
  `compartilhamento` TINYINT NOT NULL,
  `aceita_comentario` TINYINT NOT NULL,
  `usuario_id` INT NOT NULL,
  `tema_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_postagem_usuario_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_postagem_tema1_idx` (`tema_id` ASC) VISIBLE,
  CONSTRAINT `fk_postagem_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `projetointegrador_ods1`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_postagem_tema1`
    FOREIGN KEY (`tema_id`)
    REFERENCES `projetointegrador_ods1`.`tema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
